### ISSUE TITLE
Nextjs에서 동적라우팅 적용하기

### ISSUE THREAD

**Issue by Synagir** [Front-line-dev/markup-educator#22]
## 개요
퀴즈 페이지마다 문제만 달라지고 기본 UI는 동일하니, 파라미터만 받아서 각기 다른 페이지를 페이지를 노출하면 될 것 같다고 생각했습니다. 

## useRouter
Next.js에서 기본적으로 제공하는 라우팅 라이브러리입니다. `router.push`를 이용하여 프로젝트 내 URL을 이동할 예정입니다.
- 관련 문서 : [Nextjs: Router Document](https://nextjs.org/docs/api-reference/next/router)

## getServerSideProps
Nextjs가 getServerSideProps 함수를 통해 받은 데이터로 페이지를 서버 사이드에서 미리 렌더링(pre-render)이 가능합니다.
- 관련 문서 : [Nextjs: getServerSideProps](https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props)

### 폴더 구조
```
pages
├── quiz.tsx
├── index.tsx
└── quiz
    └── [id].tsx
```

### pages/quiz.tsx
```tsx
import { useRouter } from 'next/router';

export default function quiz() {
  const router = useRouter();
  const moveNewAddress = (id: number) => {
    router.push(
      {
        pathname: `/quiz/${id}`,
        query: {
          id,
        },
      },
      `/quiz/${id}`
    );
  };

  return (
    <div className={styles.wrap}>
      <button type="button" onClick={() => moveNewAddress(1)}>
        1 클릭 !!
      </button>
      <button type="button" onClick={() => moveNewAddress(2)}>
        2 클릭 !!
      </button>
    </div>
  );
}

```

- 첫번째 버튼을 클릭하면 /quiz/1 로 이동하고, 두번째 버튼을 클릭하면 /quiz/2로 이동합니다.
- router를 push 할 때 query도 같이 전송하여 동적인 페이지를 만들 수 있습니다.

### pages/quiz/[id].tsx
```tsx
import { useRouter } from 'next/router';

export default function MainQuiz() {
  const router = useRouter();
  const { id } = router.query;
  return (
    <div>
      <p>{id}</p>
    </div>
  );
}

export async function getServerSideProps(context) {
  const { id } = context.params;
  return {
    props: {
      id,
    },
  };
}
```
- pages 하위 폴더에 quiz를 만들고, id값을 동적으로 받기 위해 [id].tsx 라고 네이밍했습니다.
- 받아온 router의 query값에서 id를 받았습니다.

## 정리
- 현재 프로젝트에서는 외부 API를 활용하는 부분은 없기에 getServerSideProps 활용성은 떨어질 것 같습니다. 위에서 보여준 예시에서 getServerSideProps 함수를 제거해도 렌더링의 문제는 없습니다(서버 사이드에서 렌더링하는 것으로 변경하는 것이기 때문에).
- 이 부분 지식이 부족해서 이슈로 간단히 작성해보았는데요, 추가적인 내용과 고칠것이 있으면 말씀해주세요.

@dnrlrl @Front-line-dev

**Comment by Front-line-dev** [comment]
드디어 다이나믹 라우팅이네요 문서 먼저 정리해주셔서 감사합니다

---

1. quiz.tsx는 삭제하는게 좋을 것 같습니다

/quiz 페이지로 갔을 때 나오는 페이지인데 또 다른 페이지를 작성해야 해서 홈페이지로 리다이렉트 시키는게 좋을 것 같습니다

퀴즈 페이지는 /quiz/1 이런식으로만 접근 가능하게 하고요

2. 동적라우팅은 useRouter와 getStaticPaths를 사용하면 될 것 같습니다

말씀대로 getServerSideProps는 next.js의 서버를 사용중일때만 작동합니다. static page 빌드시에는 getStaticPaths가 필요할 것 같습니다

getStaticPaths에 대한 내용은 다음과 같습니다
https://nextjs.org/docs/api-reference/data-fetching/get-static-paths

다음은 getStaticPaths를 사용한 예제입니다
https://nextjs.org/learn/basics/dynamic-routes

---

제가 생각해봤는데 퀴즈는 각각의 json 파일이고 nextjs 빌드시 특정 폴더의 모든 json을 읽어서 static page로 빌드 할 생각입니다

따라서 동적라우팅 적용을 원활하게 하기 위해서는 샘플 퀴즈 json이 있으면 편할 것 같네요

아래와 같이 샘플 json을 몇개 작성해서 테스트해보면 좋을 것 같습니다

- 1.json
```json
{
  "name": "환영 페이지",
  "category": "basic",
  "userHTML": "<h1>Hi</h1>",
  "userCSS": "h1 { font-size: 2em; }",
  "answerHTML": "<h1>Hi</h1>",
  "answerCSS": "h1 { font-size: 2.5em; }"
}
```

**Comment by Synagir** [comment]
@Front-line-dev 
민성님, 의견 감사합니다~! 👍 

> 1. quiz.tsx는 삭제하는게 좋을 것 같습니다

제가 이동 버튼을 구현 예시를 만드려고 만든 파일인데, 현재 프로젝트에 적용되는 것처럼 작성한 것처럼 보여 오해가 생긴 것 같습니다. 민성님 말씀대로 홈에서 퀴즈를 클릭하면 바로 이동하는 것으로 생각했고, 현재 예시를 든 부분은 링크 이동을 보여주기 위해 작성했습니다. 다음에 요런 관련 문서를 작성할 때는 충분한 설명과 예시임을 사전에 작성해야겠군요.. ㅎㅎ;

> 제가 생각해봤는데 퀴즈는 각각의 json 파일이고 nextjs 빌드시 특정 폴더의 모든 json을 읽어서 static page로 빌드 할 > 생각입니다

구체적인 구현 방안을 알려주셔서 감사합니다! 코드 작성할 때 참고하도록 하겠습니다. 😄
