### ISSUE TITLE
문제 풀면서 나왔던 버그

### ISSUE THREAD

**Issue by Synagir** [Front-line-dev/markup-educator#68]
1. 이전에 테스트했던 부분때문인지 다음 문제로가 나오지 않는 버그

![image](https://github.com/Front-line-dev/markup-educator/assets/47382819/60bb6550-bfd9-44d4-bc1a-7234403dcf8b)

2.  윈도우에서 /quiz/[id] 페이지에서 퀴즈 리스트를 불러오면 우측 스크롤때문에 움직이는 현상

**Comment by Front-line-dev** [comment]
nextjs `Link`를 사용했을 때 `quizCleared` 상태가 초기화되지 않는 이슈는 해결할 수 있을 것 같습니다

2번째 이슈인 우측 스크롤 때문에 움직이는 현상은... 해결할 수 있지만 어떻게 해결해야할지 모르겠네요

우측 스크롤바를 자리를 차지하지 않게 하고 투명화 시키면 될까요?

![image](https://github.com/Front-line-dev/markup-educator/assets/67293994/4ed2be32-3443-49cd-9139-116dcd8af44d)
