### ISSUE TITLE
퀴즈 코드 에디터

### ISSUE THREAD

**Issue by Front-line-dev** [Front-line-dev/markup-educator#9]
- 퀴즈 코드 에디터
    - [모바일] HTML, CSS 탭 버튼
    - 홈, 퀴즈페이지에서는 수정 가능. 정답 페이지에서는 수정 불가능
- 코드 결과 화면
    - [모바일] 사용자 코드 렌더링 결과 화면, 목표 화면 탭 버튼

**Comment by Front-line-dev** [comment]
> https://uiwjs.github.io/react-codemirror/

## Use initialState to restore state from JSON-serialized representation

```
      onChange={(value, viewUpdate) => {
        localStorage.setItem('myValue', value);

        const state = viewUpdate.state.toJSON(stateFields);
        localStorage.setItem('myEditorState', JSON.stringify(state));
      }}
```

- value: 코드미러에서 작성되어있는 문자열
- viewUpdate.state: 코드미러의 상태. 히스토리, 선택한 위치 등 다양한 상태를 저장하고 있음

새로고침시 state까지 복구할 필요는 없을 것 같아서 value만 사용

**Comment by Front-line-dev** [comment]
![dia](https://github.com/Front-line-dev/markup-educator/assets/67293994/7852aaba-6015-4cb2-b93e-51572f645383)

**Comment by Front-line-dev** [comment]
간단하다면 간단하지만 위의 프로세스가 20개의 순서작업, 각각의 작업이 큰 작업이라고 가정해봤습니다

구현할 때 하나의 함수가 비대해지거나 함수들끼리 묶여있어서 더 나은 방법이 없나 고심해봤습니다

https://refactoring.guru/ko/design-patterns/chain-of-responsibility

위와 같이 특정 디자인 패턴을 사용하면 좀 더 나은 코드를 작성할 수 있습니다

리액트에서 사용하는것이니, 리액트가 제공해주는 디자인패턴인 옵저버 패턴을 사용하면 될 것 같습니다

필요한 함수들도 useEffect와 같이 이미 정의되어있습니다

그래서 요 며칠간 useEffect를 살펴보고 있는데 생각보다 구현이 복잡합니다

https://www.rinae.dev/posts/a-complete-guide-to-useeffect-ko

또한 이 글을 읽으면서 알게된 사실인데 state가 바뀔때마다 컴포넌트가 새로 만들어지고, UI가 새로 그려져서 엄청난 성능 문제가 있을 것 같습니다

일단 만들고 성능 테스트를 한 뒤, useCallback, memo와 같은 도구들도 최적화를 시킬 필요도 있겠습니다

조만간 useEffect를 사용해서 위의 프로세스를 구현해서 올려보겠습니다

**Comment by Synagir** [comment]
- 퀴즈 화면의 두 에디터가 동일하지 않는 이슈
